services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
      - 8000:5000
    volumes:
      - ./:/app

volumes:
  pgdata: